name: Deploy To Dockerhub(Latest)

on:
  push:
    branches: [ master ]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Setup env
        run: |
          export COMMIT_HASH=$GITHUB_SHA
          export COMMIT_TIME=$(git show -s --format=%ci $COMMIT_HASH)
          export CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - name: Build
        run: mkdir -p ./temp && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.BuildTag=$COMMIT_HASH -X main.BuildTime=$CURRENT_TIME -X main.CommitTime=$COMMIT_TIME -s -w --extldflags '-static -fpic'" -o ./temp/linux_amd64/hitokoto_notification_worker main.go
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hitokoto/notification-worker:latest
          file: ./manifest/docker/Dockerfile
          context: .
